### PR TITLE
created the BaseEntity Class

### PR DESCRIPTION
**Pull request by JeffersonBenzan**

### CODE REVIEW

**Comment by Willjobs94** [comment]
This is great to start with, apart from including the class, make all the other entity classes that we have to inherit from this one.

**Comment by Willjobs94** [comment]
Also, rename the `Artist` class to `Actor`

**Comment by JeffersonBenzan** [comment]
Done! The BaseEntity Class was inherited and also rename de Artist Class

**Review by Willjobs94 — APPROVED** [review]
Great job

**Pull request merged**
